# Generated by Django 5.0.6 on 2024-12-19 13:41

import manage_cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalcar",
            name="car_id",
            field=models.AutoField(
                default=manage_cars.models.generate_random_car_id,
                max_length=5,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
