# Generated by Django 5.1 on 2024-12-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cars', '0002_alter_rentalcar_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcar',
            name='car_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
