# Generated by Django 5.0.6 on 2024-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manage_cars",
            "0002_remove_transaction_car_id_transaction_car_dealer_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealer",
            name="user",
        ),
        migrations.AddField(
            model_name="dealer",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="dealer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
