# Generated by Django 5.0.6 on 2024-12-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_cars", "0003_remove_dealer_user_dealer_contact_number_and_more"),
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalcar",
            name="dealer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="user_auth.dealer",
            ),
        ),
        migrations.DeleteModel(
            name="Dealer",
        ),
    ]
